os: linux

language: go

go: 
  - 1.13.x

sudo: required

arch:
  - ppc64le

script:
  - sudo apt-get install build-essential
  - git clone https://github.com/operator-framework/operator-sdk.git
  - cd ./operator-sdk/
  - git checkout tags/v0.9.0
  - make install
  - echo $GOPATH
  - mkdir ./v0.9.0
  - cp -rp /home/travis/gopath/bin/operator-sdk ./v0.9.0
  - ./v0.9.0/operator-sdk --help
